kind: Template
apiVersion: v1
objects:
  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      name: "openshift-pipelines-from-jenkins"
    spec:
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2
      resources:
        limits:
          cpu: "1"
          memory: "1024m"
      source:
        type: "Git"
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: "master"
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: openshift-pipelines-backend-from-jenkins
    spec:
      template:
        metadata:
          labels:
            name: "openshift-pipelines-selector-jenkins"
        spec:
          containers:
            - name: "openshift-pipelines-service-from-jenkins"
              image: "docker.io/hakdogan/openshift-pipelines:latest"
              ports:
                - containerPort: 8080
                  protocol: "TCP"
              livenessProbe:
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 2
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 2
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
    replicas: "${{REPLICA_COUNT}}"
  - kind: Service
    apiVersion: v1
    metadata:
      name: "openshift-pipelines-jenkins-service"
      annotations:
        description: "Exposes the application pod"
    spec:
      ports:
        - name: "from-docker-source"
          port: 8080
          targetPort: 8080
          protocol: "TCP"
      sessionAffinity: None
      type: ClusterIP
      selector:
        name: "openshift-pipelines-selector-jenkins"
    status:
      loadBalancer: {}
  - kind: Route
    apiVersion: v1
    metadata:
      name: openshift-pipelines-router-jenkins
    spec:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: openshift-pipelines-jenkins-service
parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Source Repository URL
    description: The URL of the openshift-pipelines project
    value: https://github.com/hakdogan/openshift-pipelines.git
    required: true
  - name: REPLICA_COUNT
    description: Number of replicas to run
    value: "1"
    required: true
message: "OpenShift Pipelines Tutorial"
metadata:
  name: "openshift-pipelines-openshift-jenkinsfile-maven"